# Домашнее задание «Библиотека numpy. Вычислительные задачи»

## Задание 1

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [31]:
import numpy as np

In [32]:
def create_array(N):
    """
    Создает numpy array с элементами от числа N до 0
    """
    return np.arange(int(N)-1, -1, -1)

In [34]:
create_array(10)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Задание 2

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [45]:
def create_diag_matrix(N):
    """
    Создает диагональную матрицу с элементами от N до 0 и считает сумму ее значений на диагонали.
    Выход в формате: matrix, summ
    """
    _matrix = np.diag(np.arange(int(N)-1,-1,-1), k=0)
    return _matrix, sum(np.diagonal(_matrix))

In [46]:
create_diag_matrix(10)

(array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]),
 45)

## Задание 3

Решите систему уравнений:  
4x + 2y + z = 4  
x + 3y = 12  
5y + 4z = -3  

In [48]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ])
b = np.array( [4, 12, -3] )

In [49]:
from numpy import linalg

In [50]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [51]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True